### ISSUE TITLE
Guzzle 7

### ISSUE THREAD

**Issue by Fossil01** [canihavesomecoffee/theTVDbAPI#14]
Any plans for latest Guzzle (7.x) support? It's holding back my application (Laravel) upgrade :-)

I think PHPUnit can also be upgraded to 9.x (maybe).

**Comment by canihavesomecoffee** [comment]
I'd have to take a look to see what's changed so determine if it's easy enough to add/upgrade.

However I'm also a bit in doubt whether or not to put more effort in this package as theTVDb announced plans to retire version 3.x early next year[1] (and launch a whole new v4.0, which likely isn't going to be compatible at all). It might be more efficient to work on a new iteration of the API that supports their 4.x that uses the newest packages where necessary... But I don't have access to that 4.x yet.

[1] Refer to https://thetvdb.com/dashboard/account/apikey and https://thetvdb.com/api-information

**Comment by Fossil01** [comment]
Hmm. Hopefully it's an easy change for now then. Really want to use Laravel 8 soon :-P

**Comment by Fossil01** [comment]
I tried updating Guzzle to ^7.0 in composer.json and ran phpunit without any errors.

**Comment by canihavesomecoffee** [comment]
@Fossil01 Good to know. I'll try the same this evening and push a release if nothing breaks :+1:

**Comment by Fossil01** [comment]
@canihavesomecoffee Cheers. I haven't tried it with the latest phpunit version though. I think 9.x is out already but I have literally zero experience with it :-)

**Comment by canihavesomecoffee** [comment]
@Fossil01 https://github.com/canihavesomecoffee/theTVDbAPI/releases/tag/1.3.0, enjoy! Turns out I still need the older PHPUnit for supporting PHP7.2, but thankfully composer allows multiple version requirements.
