### ISSUE TITLE
Actor Model - NULL imageauthor

### ISSUE THREAD

**Issue by tntsoft** [canihavesomecoffee/theTVDbAPI#2]
> The type of the "imageAuthor" attribute for class "CanIHaveSomeCoffee\TheTVDbAPI\Model\Actor" must be one of "int" ("NULL" given)

To fix, please change Model/Actor.php line 60 from
`     * @var integer`
to
`     * @var integer|null`

**Comment by tntsoft** [comment]
Submitted a pull request that fixes this. Please merge.

**Comment by canihavesomecoffee** [comment]
Hi @tntsoft, you can usally just mention in your PR that it closes this issue ;)

**Comment by canihavesomecoffee** [comment]
Released 1.1.1 with the fix, thanks again for contributing :1st_place_medal:!
