### ISSUE TITLE
TVDB is disabling their current API on Oct 1st

### ISSUE THREAD

**Issue by Fossil01** [canihavesomecoffee/theTVDbAPI#20]
When will 4.x branch go live?

**Comment by canihavesomecoffee** [comment]
Whenever I find time to add the last end points and do enough checks to ensure it's a decent state... I've gotten the mail too, so  I'm aware of the deadline.

**Comment by canihavesomecoffee** [comment]
@Fossil01 I've published a new beta version and I intend to go live with that one by the end of the week. Could you (if you have time) do a quick test and provide me with feedback?

**Comment by Fossil01** [comment]
Won't be home for a few days. Maybe @DariusIII could help.

**Comment by canihavesomecoffee** [comment]
Closed by release of v2.0.0.0.

If you find bugs in this new release, please let me know and I'll fix ASAP :+1:
