### ISSUE TITLE
Packager preventing upgrade to Laravel 10

### ISSUE THREAD

**Issue by Fossil01** [canihavesomecoffee/theTVDbAPI#29]
Might need some dependencies bumped like here: https://github.com/DariusIII/theTVDbAPI/commit/89240c61214869edbfc6c5757856304758140655

**Comment by canihavesomecoffee** [comment]
Thanks for reporting. I'll try to free up a bit of time this weekend to look at that, or perhaps @DariusIII would be willing to create a PR if they already tested the upgrade themselves :)

**Comment by canihavesomecoffee** [comment]
Closing, see https://github.com/canihavesomecoffee/theTVDbAPI/releases/tag/2.1.8

Should work (tests don't indicate a failure when ran on newer php versions); if it were the case, let me know :)
