### ISSUE TITLE
Possible to search just by title?

### ISSUE THREAD

**Issue by ghost** [canihavesomecoffee/theTVDbAPI#31]
I am having an issue where TVDB returns a lot of crap shows when I search for this query `DAVE 2020` or `DAVE (2020)`.

It seems to return shows with the word `dave` in either some URL or the network but the word is not present in the title at all. For example it returns `The Island (2022) (UK)`

So I was wondering if it is possible to just search by title?

**Comment by canihavesomecoffee** [comment]
What's the code you're currently using for this? Just the regular endpoint call (`search("DAVE 2020")`)?

There are additional arguments available (via `$optionalParameters`) that should allow you to tune the search, i.e. `search('DAVE', ['year' => 2020, 'type' => 'series'])`.

As far as I can see in the documentation (https://thetvdb.github.io/v4-api/#/Search/getSearchResults), the query should already be limited to main title, translations and aliases.
