### ISSUE TITLE
How would I fetch all episodes for a show?

### ISSUE THREAD

**Issue by Fossil01** [canihavesomecoffee/theTVDbAPI#6]
It looks like it only returns page 1, but the description for getEpisodes() shows: All episodes for a given series. Paginated with 100 results per page.

How would I just feed it a TVDB ID and make it return all episodes at once?

It looks like getLastPage() and getNextPage() is not used anywhere.

**Comment by canihavesomecoffee** [comment]
You cannot feed it just a TVDb id and get it all back with the current API unfortunately.

What can be done is call it in a loop, setting the `$page` variable with `getNextPage()` from the current request, until that becomes 0.

**Comment by Fossil01** [comment]
Ok, I figured. Was just thrown off by the description of the function :-)

**Comment by canihavesomecoffee** [comment]
Well, I could definitely make the docstring of that function more clear then.

Alternatively, I might change the behaviour of the function a little so that if you request page=-1 (for example, and set that as default value) it does that loop for you.

**Comment by Fossil01** [comment]
That would be awesome!

**Comment by canihavesomecoffee** [comment]
I'll try to take it along in one of the next releases then.

**Comment by Fossil01** [comment]
Any idea how long that'll take? I wanted to try to have a go at it but can't even get the package to run on my dev machine. It bitches about phpdocumentor/reflection-docblock not being installed. Just ran composer require  canihavesomecoffee/thetvdbapi

**Comment by canihavesomecoffee** [comment]
Throw out phpunit and you should be fine:

`composer show --tree` shows me that the `phpdocumentor/reflection-docblock` dependency is required by `phpspec/prophecy`, which in turn is required by `phpunit/phpunit`.

I'm currently working on an update though, but it'll be a new method (since I don't want to break existing clients by changing behavior).

**Comment by Fossil01** [comment]
That is totally fine 👍 👍

**Comment by canihavesomecoffee** [comment]
https://github.com/canihavesomecoffee/theTVDbAPI/releases/tag/1.2.3 :)

**Comment by Fossil01** [comment]
Cheers, will test.

**Comment by Fossil01** [comment]
Tested and it works as expected. Thanks 👍  Saves me the headache of messing with custom forks till this was merged :-)

**Comment by canihavesomecoffee** [comment]
Happy to hear :)

Don't hesitate to open new issues if you see further areas of improvement :+1:
